apiVersion: v1
kind: Service
metadata:
    name: productmicroservice
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
    type: LoadBalancer
    loadBalancerIP: #loadBalancerIP#
    ports:
      - port: 8080
    selector:
      app: productmicroservice
